# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: ACIC
    url: https://aviationcharges.iata.org
  - name: SNAP
    url: https://supplylink.iata.org
  - name: WebStar Extranet
    url: https://webstar.iatan.org/WebStarExtranetWEB
  - name: PASS
    url: https://pass.iata.org

status-website:
  cname: upptime.js.org
  name: Upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
