# Change these first
owner: shomaru # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: ACIC
    url: https://aviationcharges.iata.org
  - name: AVSEC
    url: https://avsec.iata.org
  - name: SNAP
    url: https://supplylink.iata.org
  - name: WebStar
    url: https://webstar.iatan.org
  - name: PASS
    url: https://pass.iata.org

status-website:
  baseUrl: /upptime
  name: Upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
workflowSchedule:
  graphs: "45 0 * * *"
  responseTime: "45 23 * * *"
  staticSite: "45 1 * * *"
  summary: "45 0 * * *"
  updateTemplate: "45 0 * * *"
  updates: "45 3 * * *"
  uptime: "15 * * * *"
