# Change these first
owner: shomaru # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: ACIC
    url: https://aviationcharges.iata.org
  - name: SNAP
    url: https://supplylink.iata.org
  - name: WebStar
    url: https://webstar.iatan.org
  - name: PASS
    url: https://pass.iata.org

status-website:
  baseUrl: /upptime
  name: Upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
workflowSchedule:
  graphs: 45 * * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "15 * * * *"
